# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
## git 克隆yelee主题到指定路径 （原仓库地址）
## git clone https://github.com/MOxFIVE/hexo-theme-yelee.git themes/yelee-pre
## 教学指导地址： https://blog.wangriyu.wang/2017/08-Hexo.html
##----------------------------------------------------------
# Site网站标题
title: Sukie's Blog
subtitle: '新世界编程'
description: 'Hello World！'
keywords:
author: Sukie
language: en ##zh-Hans #en
timezone: ''

# 法一
# 统计字数和阅读时长
## npm i --save hexo-wordcount
## themes/yelee/layout/_partial/post/tag.ejs
## themes/yelee/source/css/_partial/tagcloud.styl
### content: “\27A4” 是 unicode 图标编码，可以换成其他的
### unicode 图标 :https://unicode-table.com/cn
### Font Awesome Icon：http://fontawesome.io/icons
# 法二
word_count: true

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: http://yoursite.com
url: https://sukie-sun.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

######文章永久链接
######永久链接的好处很多，最直接的，无论以后改变了文章标题还是 markdown 文档的名字，
######永久链接都不会改变，我们的文章链接就不会失效 ：
######安装插件，这个插件会根据文章名字生成一个随机的字符串：
###### npm install hexo-abbrlink --save
####permalink: category/:abbrlink.html
####abbrlink:
####  alg: crc32  # 算法：crc16(default) and crc32
####  rep: hex    # 进制：dec(default) and hex
  
  
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
    -  README.md
    -  baidu_verify.html
    -  google_verify.html
    -  404/404.html
    -  static/**

## 添加二次元人物
## 安装插件 npm install -save hexo-helper-live2d
## npm install --save live2d-widget-model-izumi
## live2d: https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d_models/live2d-widget-model-chitose ##live2d-widget-model-izumi ##加载本地 model 文件
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    position: right
    width: 150
    height: 300
    hOffset: -50
    vOffset: -85
  mobile:
    show: true
  react:
    opacityDefault: 0.9
    opacityOnHover: 0.3

##----------------------------------------------------------
   
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
##  Hexo添加图片到博客中 ：生成一个以文章名称命名的文件夹
##post_asset_folder: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
##theme: landscape   
theme: yelee

# Deployment
## Docs: https://hexo.io/docs/deployment.html
## 浏览器访问方式： https://sukie-sun.github.io
deploy:
  type: git
  repo: git@github.com:sukie-sun/sukie-sun.github.io.git
# repo: git@gitee.com:sunrisefly/sunrisefly.git
  branch: master 
  
  
## index_generator:
##   per_page: 15

archive_generator:
  per_page: 0
  yearly: true
  monthly: true

tag_generator:
  per_page: 0

disqus_shortname: 

search:
  path: search.xml
  field: post

# https://github.com/unhealthy/hexo-all-minifier
html_minifier:
  enable: false
  exclude: 

css_minifier:
  enable: false
  exclude: 

js_minifier:
  enable: false
  mangle: true

image_minifier:
  enable: false
  interlaced: true
  multipass: true
  optimizationLevel: 2
  pngquant: false
  progressive: true  
  